# Generated by Django 4.1.2 on 2022-11-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='first_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='avatar',
            field=models.ImageField(upload_to='user/avatar', verbose_name='Фото пользователя'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Номер телефона'),
        ),
    ]
