# Generated by Django 4.1.2 on 2022-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_usernet_first_login_alter_usernet_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='avatar',
            field=models.ImageField(upload_to='resource', verbose_name='Фото пользователя'),
        ),
    ]
