# Generated by Django 4.1.2 on 2022-11-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_usernet_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='avatar',
            field=models.ImageField(upload_to='user/avatar', verbose_name='Фото пользователя'),
        ),
    ]
